- name: Install and Build
        env:
          VITE_SUPABASE_URL: "https://ilufkshwfxggslskftzr.supabase.co"
          VITE_SUPABASE_ANON_KEY: "sb_publishable_86PL3iy2xO5odeKsP7RMPA_txzMlsIS"
        run: |
          bun install
          bun run build
